Module Type TYPEOID_SIG.
	Parameter	TYPE							:	Type.
		Parameter	TYPEOID_EQUIVALENCE			:	TYPE->TYPE->Type.
			Parameter	EQUIVALENCE_REFLEXIVE	:	forall t:TYPE, TYPEOID_EQUIVALENCE t t.
			Parameter	EQUIVALENCE_SYMMETRIC	:	forall x y:TYPE, (TYPEOID_EQUIVALENCE x y) -> (TYPEOID_EQUIVALENCE y x).
			Parameter	EQUIVALENCE_TRANSITIVE	:	forall x y:TYPE, (TYPEOID_EQUIVALENCE x y) -> (TYPEOID_EQUIVALENCE y x).
End TYPEOID_SIG.